-- KANJI-6: source and merge metadata for expanded learning datasets.
-- Generated at: 2026-05-26T17:13:09+09:00 (Asia/Seoul)
-- Run in Supabase SQL editor or via `supabase db push` after review.

alter table public.kanji
  add column if not exists source text not null default 'legacy_excel',
  add column if not exists external_id text,
  add column if not exists source_version text,
  add column if not exists quality_status text not null default 'reviewed',
  add column if not exists meaning_source text not null default 'legacy_excel',
  add column if not exists is_common boolean not null default false,
  add column if not exists priority_rank integer,
  add column if not exists tags text[] not null default '{}',
  add column if not exists updated_at timestamptz;

alter table public.words
  add column if not exists source text not null default 'legacy_naver',
  add column if not exists external_id text,
  add column if not exists source_version text,
  add column if not exists quality_status text not null default 'reviewed',
  add column if not exists meaning_source text not null default 'legacy_naver',
  add column if not exists is_common boolean not null default false,
  add column if not exists priority_rank integer,
  add column if not exists tags text[] not null default '{}',
  add column if not exists updated_at timestamptz;

create index if not exists kanji_source_external_id_idx
  on public.kanji (source, external_id);

create index if not exists words_word_reading_idx
  on public.words (word, reading);

create index if not exists words_source_external_id_idx
  on public.words (source, external_id);

create table if not exists public.data_source_versions (
  id bigint generated by default as identity primary key,
  source text not null,
  source_version text not null,
  license text not null,
  source_url text not null,
  sha256 text not null,
  fetched_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (source, source_version, sha256)
);
